#!/usr/bin/env bash

#get the vars
echo "Name of new component"
read componentName

#make template partial
touch ../src/partials/$componentName.html
echo "Created $componentName.html"

#make Sass partial
touch ../src/assets/scss/components/_$componentName.scss
echo "Created _$componentName.scss"

#add to scss/_init
echo "@import 'components/$componentName';" >> ../src/assets/scss/_init.scss 
echo "initalized the sass partial"

echo "Done :-)"

